### ISSUE TITLE
Performance: make worker prefetch data for next task

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#101]
Most tasks fetches data, do some processing, and saves data. Let a worker fetch next task data while doing processing. Saving data from a task can also being done in parallel.

For example, while inference is running in a chunk, them images for the next run of inference can be prefetch. And also the affinities can be saved while inference is happening.
This way we can have 100% gpu utilization at the cost of having more memory being used. That's why probably have a flag to disable this in the case that computation time is small or when not enough RAM is available.

**Comment by william-silversmith** [comment]
I'm not sure this is super useful if inference takes hours, you might save a few minutes at the expense of more complex infrastructure. Part of the trick is that you'd have to lease a second task early in order to know what to download, and if you retain the lease other tasks can get to it (which starts to become important once the number of tasks becomes similar to the number of machines otherwise you get a big slowdown of about 2x the number of pods at the end). If you lease and the release, that might work, but you probably won't be able to lease the same task again.

Some of these problems go away if we have control of the queue infrastructure. My criticisms above are particular to Google's Task Queue.

**Comment by nkemnitz** [comment]
Now handled in [Igneous](https://github.com/seung-lab/igneous)
