### ISSUE TITLE
dynamic dependency of tasks

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#148]
currently, all the dependency of tasks should be full filled before usage and some of them needs compilation, such as Mesher. This seems not quite portable.

Since the packages could be dynamically loaded in python, we can simply put the import in each task class?

**Comment by tartavull** [comment]
Many python packages (like numpy) requires compilation during installation.
The most complicated part for us is that we required a fairly recent version of gcc.

We provide docker images for when we don't want to compile https://hub.docker.com/r/tartavull/neuroglancer

My intuition is that the root cause is that the package is harder than install than it should and that we should try to solve that.

**Comment by william-silversmith** [comment]
Just chiming in, we solved the gcc version problem in https://github.com/seung-lab/neuroglancer/pull/140

**Comment by william-silversmith** [comment]
If that was the only reason that is. I think it was.

**Comment by tartavull** [comment]
thanks, also https://github.com/seung-lab/neuroglancer/issues/128

**Comment by nkemnitz** [comment]
Now handled in [Igneous](https://github.com/seung-lab/igneous)
