### ISSUE TITLE
Lock EM data download to singlemip level depending on view or user settings

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/neuroglancer#202]
This is a break out of #191.

Neuroglancer downloads EM data from all mip levels down to the currently deemed optimal. When zoomed in to a single neuron, all higher mip levels are downloaded before downloading the mip level of interest. This is wasteful, blocks other functionality and fills the memory on the users workstation without adding a significant benefit. 

I propose to follow an approach that locks the download to a single mip level. This mip level is chosen based on the zoom level and or user setting. Neuroglancer appears to limit the download based on the zoom level already but only towards lower mip levels. 

Features to be added:
- avoid downloading EM data from all but the lowest chosen mip level.
- allow the user to lock his / her mip level to overwrite this decision. At least the user should be able to set the lowest mip level to be loaded. Eg. the user can set the lowest mip level to 1 to avoid downloading data from mip 0 regardless of the zoom level.

**Comment by nkemnitz** [comment]
This hints at a problem with our current downsampling approach.

We do want to show the users a cheap, low-resolution preview, while high-res data is being loaded. Our current downsampled layers however are not _cheap_, as the number of voxel for each chunk remains the same: We downsample by a factor of 2, but double the edge length of the cube. Instead of downloading a MIP-hierarchy of 4/3 of the original data's size, we download *n* times the original data's size, where *n* is the number of downsampled layers.
The effect is strongest when first loading the page and weaker when the user pans through the dataset, but still far higher than expected.

Todo: Lower chunk size for downsampled data accordingly. Check at which point the increased number of requests will have a negative impact. (At the lowest-resolution layer, a chunk would otherwise become 1 voxel large)

**Comment by nkemnitz** [comment]
Added in #243 - thanks @manuel-castro !
