### ISSUE TITLE
segmentation_with_graph

### ISSUE THREAD

**Issue by fcollman** [seung-lab/neuroglancer#279]
so the new format of having segmentation layers that are with graphs be different than 'segmentation' layers have broken all existing links.  Is there a good reason for this extension? It would seem like the source being graphene would allow the code to know which kind of object to instantiate.  I'm guessing this has to do with trying to integrate the multi-cut interface, but I wanted to try to probe a little bit to see if this can be done in a none breaking way.

**Comment by nkemnitz** [comment]
The segmentation_with_graph user layer was added to keep all graph related things out of the regular SegmentationUserLayer (`segmentation`). That makes the code easier to read and maintain and as you noted, allows me to get the Multi-Cut integrated in a less ugly way.

I was _partly_ aware of the `segmentation` -> `segmentation_user_layer` issue that would arise: The `info` files that the graph servers provide currently all specify `segmentation` as volume type. That's why I currently override the volume type for graphene data sources: https://github.com/seung-lab/neuroglancer/blob/c6d31666bd462b0962aca1bbc4f59979b6eb58a6/src/neuroglancer/datasource/graphene/frontend.ts#L177
Neuroglancer however has another way to determine which UserLayer to create, and that one takes precedence over the volume type specified in the info file: It's first looking if there is already a _layer_ type set in the JSON state. Presumably to speed up loading, but maybe also because that's similar to how Neuroglancer allows you to override mesh paths, skeleton paths and alike.

PR https://github.com/seung-lab/neuroglancer/pull/280 would semi-automatically resolve the issue, but I don't like it very much... It's a hack to deal with backward compatibility issues for a feature that is still in early development / version 0.x.

**Comment by fcollman** [comment]
thanks nico for considering this.. I think we will ultimately be able to help those with shortened links by dynamically reformatting their links on the backend.. the question then comes down to how to deal with retiring of old appspot branch deployments.
