### ISSUE TITLE
[graphene]: add timestamp setting

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/neuroglancer#284]
The PyChunkedGraph supports `root_id` retrieval with a timestamp. Currently, neuroglancer only allows retrieval of the latest `root_id`. I would like to make this query option available to the user, eg. through a box in the graphene segmentation layer.

Proofreading should be disabled when any time but the current time is selected.

**Comment by nkemnitz** [comment]
Do you have typical work flow or can describe a task the user would try to accomplish with this date selection box?

I am trying to figure out what the expected behavior would be for modifying the date (set it back and forth several times) while root objects are already selected: Would I load all associated `formerParents` / `laterParents` everytime? That could lead to an "explosion" of selected segments after a few iterations. Should I 

Also, while I can prevent sending split/merge requests through the Neuroglancer interface, the graph server should still check if the request looks reasonable. For example, if the given `rootObjectID` is the most recent.

**Comment by sdorkenw** [comment]
We combine annotations and segmentation at specific timestamps (materialization). Hence, users run their analysis with an older than the current state of the segmentation. It would be helpful to configure neuroglancer to reflect that state.

I agree that there needs to be some specific behavior when it comes to selected root ids. For now, I would just deselect all root ids when the timestamp is changed (and have a popup warning about this?). 

Mergers and splits are independent of what the root id is and the graph server can still process them. Since the "shown" root ids are not send to the graph server, it has no way of telling what the user saw when making that call. I suggested this freeze because (1) the users decision is not based on the most recent state of the segmentation and (2) the result would not be shown because it is more recent than the selected timestamp. I am basically arguing that it does not make sense from a frontend persepctive to allow the user to make proofreading changes, the graph server is agnostic to that.

**Comment by ogewan** [comment]
Implemented in https://github.com/seung-lab/neuroglancer/pull/341
