### ISSUE TITLE
Specify file name for annotations 

### ISSUE THREAD

**Issue by ashwinvish** [seung-lab/neuroglancer#434]
Currently when the annotation are exported the file name is annotiatons.cvs. I would like to add a feature that lets the user specify the file name before downloading.

**Comment by ashwinvish** [comment]
In thinking a bit more, since it is possible to specify a name to the layer (upper green bar), it may be easier to download with the name of the layer.

**Comment by manuel-castro** [comment]
From what I recall, specifying the name at export time is easier to implement, because of the way neuroglancer is structured the export feature does not have access to the layer name currently. However I think it's probably the way to go. A popup button or input box would be easier to implement, but a bit more obtrusive.

**Comment by manuel-castro** [comment]
Addessed by 15b66ab
