### ISSUE TITLE
meshes do not show up in Chrome

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#487]
it works in Firefox. 

My chrome:
Version 83.0.4103.116 (Official Build) (64-bit)

OS: Ubuntu 18.04

**Comment by akhileshh** [comment]
@jingpengw is this still an issue? Can you provide more details? Layer link?

My chrome verion is `Version 87.0.4280.88 (Official Build) (64-bit)` on `Ubuntu 20.04.1 LTS`, I haven't faced any issues with different servers since early last year.

Closing the issue for now, feel free to reopen if it happens again.
